# Generated by Django 4.0.3 on 2022-04-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=100, unique=True, verbose_name='tel')),
                ('lat', models.FloatField(max_length=10, verbose_name='lat')),
                ('lon', models.FloatField(max_length=10, verbose_name='lon')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cientes',
            },
        ),
    ]
