# Generated by Django 4.0.3 on 2022-04-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_alter_cliente_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tel',
        ),
        migrations.AddField(
            model_name='cliente',
            name='address',
            field=models.CharField(blank=True, max_length=120, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cost',
            field=models.CharField(default=0, max_length=5, verbose_name='precio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='name',
            field=models.CharField(blank=True, max_length=51, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='service',
            field=models.CharField(choices=[('NOR', 'Normal'), ('FLE', 'Flete'), ('RRP', 'RRPP'), ('FBA', 'FB Ads'), ('ORG', 'Orgánico'), ('GOA', 'Google Ads'), ('COM', 'Combo'), ('OTR', 'Otro')], default='NOR', max_length=10, verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('COT', 'Cotizado'), ('EJE', 'Ejecutado'), ('NEG', 'L.negra')], default='COT', max_length=10, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tel1',
            field=models.CharField(blank=True, max_length=8, verbose_name='telefono 1'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tel2',
            field=models.CharField(blank=True, max_length=12, verbose_name='telefono 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lat',
            field=models.FloatField(max_length=10, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lon',
            field=models.FloatField(max_length=10, verbose_name='longitud'),
        ),
    ]
