# Generated by Django 4.0.3 on 2022-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_remove_cliente_tel_cliente_address_cliente_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel1',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='telefono 1'),
        ),
    ]
