# Generated by Django 4.0.3 on 2022-04-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_alter_cliente_tel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod',
            field=models.CharField(blank=True, max_length=10, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='service',
            field=models.CharField(choices=[('NOR', 'Normal'), ('FLE', 'Flete'), ('RRP', 'RRPP'), ('FBA', 'FB Ads'), ('ORG', 'Orgánico'), ('GOA', 'Google Ads'), ('COM', 'Combo'), ('MKP', 'Market Place'), ('OTR', 'Otro')], default='NOR', max_length=10, verbose_name='servicio'),
        ),
    ]
