# Generated by Django 4.0.3 on 2022-04-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_cliente_cod_alter_cliente_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cost',
            field=models.IntegerField(default=0, max_length=5, verbose_name='precio'),
        ),
    ]
