# Generated by Django 4.0.3 on 2022-04-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0007_alter_cliente_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod',
            field=models.IntegerField(blank=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='precio'),
        ),
    ]
