# Generated by Django 4.0.3 on 2022-04-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0009_alter_cliente_tel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel2',
            field=models.CharField(blank=True, max_length=12, verbose_name='telefono 2'),
        ),
    ]
