# Generated by Django 4.0.3 on 2022-04-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0011_alter_cliente_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.CharField(blank=True, max_length=12, verbose_name='usuario'),
        ),
    ]
