# Generated by Django 4.0.3 on 2022-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0013_alter_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('CLC', 'Cliente Confirmar'), ('CLX', 'Cliente Cancelar')], default='ADM', max_length=10, verbose_name='usuario'),
        ),
    ]
