# Generated by Django 4.0.3 on 2022-04-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0014_cliente_updated_at_alter_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('COT', 'Cotizado'), ('EJE', 'Ejecutado'), ('NEG', 'L.negra')], default='COT', max_length=3, verbose_name='estado'),
        ),
    ]
