# Generated by Django 3.2.13 on 2022-04-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0016_alter_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Limpieza de Pozos | Cotiza ', max_length=70)),
                ('h1', models.CharField(default='Encuentra tu ubicación', max_length=255)),
                ('metaDescription', models.TextField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Configuración',
            },
        ),
    ]
