# Generated by Django 3.2.13 on 2022-04-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0017_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='ogDescription',
            field=models.TextField(blank=True, default='', max_length=155),
        ),
    ]
