# Generated by Django 3.2.13 on 2022-04-24 22:15

from django.db import migrations, models
import mapa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0018_siteconfiguration_ogdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='ogImage',
            field=models.FileField(default='', upload_to='mapa/', validators=[mapa.validators.validate_file_extension]),
        ),
    ]
