# Generated by Django 4.0.3 on 2022-03-27 15:14

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='titulo')),
                ('description', models.TextField(blank=True, default='', max_length=250, verbose_name='contenido')),
                ('svg', models.FileField(blank=True, default='', upload_to='icon/', validators=[main.validators.validate_file_extension])),
                ('display', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Alcance',
                'verbose_name_plural': 'Alcances',
                'ordering': ['order'],
            },
        ),
    ]
