# Generated by Django 4.0.3 on 2022-03-29 20:43

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQuien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='titulo')),
                ('svg', models.FileField(blank=True, default='', upload_to='icon/', validators=[main.validators.validate_file_extension])),
                ('display', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'A quien',
                'verbose_name_plural': 'A quienes atendemos',
                'ordering': ['order'],
            },
        ),
    ]
