# Generated by Django 3.2.13 on 2022-04-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={},
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_name',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='title',
            field=models.CharField(default='Limpieza pozos Santa Cruz', max_length=255),
        ),
    ]
