# Generated by Django 3.2.13 on 2022-04-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_siteconfiguration_h1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='maintenance_mode',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='metaDescription',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='title',
            field=models.CharField(default='Limpieza de Pozos | Santa Cruz', max_length=70),
        ),
    ]
