# Generated by Django 3.2.13 on 2022-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220424_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='metaDescription',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
