# Generated by Django 3.2.13 on 2022-04-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_siteconfiguration_metadescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='alt',
        ),
    ]
