# Generated by Django 3.2.13 on 2022-04-24 22:14

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_banner_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='ogDescription',
            field=models.TextField(blank=True, default='Servicio de limpieza de pozos y c&aacute;maras s&eacute;pticas en Santa Cruz y sus provincias. Cotiza en l&iacute;nea...', max_length=155),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ogImage',
            field=models.FileField(default='', upload_to='main/', validators=[main.validators.validate_file_extension]),
        ),
    ]
