# Generated by Django 3.2.13 on 2022-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220424_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='ogDescription',
            field=models.TextField(blank=True, default='Servicio de limpieza de pozos y cámaras sépticas en Santa Cruz y sus provincias. Cotiza en línea...', max_length=155),
        ),
    ]
