"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-71lff=*x2xo9u^--wiq7v2&&q3+r0xg6bmk51yqv*-q8(&*azc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [    
    # 'django.contrib.sites',
    'grappelli',
    # 'constance',
    # 'constance.backends.database',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'livereload',
    'svg',
    'import_export',
    'rest_framework',
    # 'solo.apps.SoloAppConfig',
    # 'grappelli.dashboard',
    'settings_app',
    'main.apps.MainConfig',
    'mapa',
]

# CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'livereload.middleware.LiveReloadScript',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'settings_app.context_processors.settings',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 'loaders': [
            #     'admin_tools.template_loaders.Loader',
            #     'django.template.loaders.filesystem.Loader',
            #     'django.template.loaders.app_directories.Loader',
            # ],
        },
    },
]

# TEMPLATE_LOADERS = [{
#     'admin_tools.template_loaders.Loader'
# }]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

# LANGUAGE_CODE = 'es-bo'
LANGUAGE_CODE = 'es-bo'

TIME_ZONE = 'UTC'

USE_I18N = True 

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

SVG_DIRS=[
    os.path.join(BASE_DIR, 'media/icon')
]

GRAPPELLI_ADMIN_TITLE = "Pozos SCZ"

# # CONSTANCE_CONFIG = {
# #     'THE_ANSWER': (42, 'Answer to the Ultimate Question of Life, '
# #                        'The Universe, and Everything'),
# # }

# CONSTANCE_ADDITIONAL_FIELDS = {
#     'yes_no_null_select': ['django.forms.fields.ChoiceField', {
#         'widget': 'django.forms.Select', 'choices': ((None, "-----"), ("yes", "Yes"), ("no", "No"))
#         }],
#     'image_field': ['django.forms.ImageField', {}]
# }

# # CONSTANCE_CONFIG_FIELDSETS = {
# #     'General Options': ('SITE_NAME', 'SITE_DESCRIPTION'),
# #     'Theme Options': ('THEME','LOGO_IMAGE'),
# # }

# CONSTANCE_CONFIG = {
#     'LOGO_IMAGE': ('default.png', 'Company logo', 'image_field'),
#     # 'MY_SELECT_KEY': ('yes', 'select yes or no', 'yes_no_null_select'),
#     # 'SITE_NAME': ('My Title', 'Website title'),
#     # 'SITE_DESCRIPTION': ('', 'Website description'),
#     # 'THEME': ('light-blue', 'Website theme'),
# }

# # CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True