# Generated by Django 4.0.3 on 2022-04-11 23:56

from django.db import migrations, models
import settings_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, default='Limpieza de Pozos | Santa Cruz', max_length=20)),
                ('main_h1', models.CharField(blank=True, default='Limpieza de Pozos Sépticos', max_length=20)),
                ('main_svg', models.FileField(blank=True, default='', upload_to='main/', validators=[settings_app.validators.validate_file_extension])),
                ('main_img', models.FileField(blank=True, default='', upload_to='main/', validators=[settings_app.validators.validate_file_extension])),
            ],
            options={
                'verbose_name_plural': 'Configuracion',
                'abstract': False,
            },
        ),
    ]
