# Generated by Django 4.0.3 on 2022-04-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_cotizasettings_alter_mainsettings_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizasettings',
            old_name='cotiza_h1',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='cotizasettings',
            old_name='cotiza_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='mainsettings',
            old_name='main_h1',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='mainsettings',
            old_name='main_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='mainsettings',
            old_name='main_svg',
            new_name='svg',
        ),
        migrations.RenameField(
            model_name='mainsettings',
            old_name='main_title',
            new_name='title',
        ),
    ]
