# Generated by Django 4.0.3 on 2022-04-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_rename_cotiza_h1_cotizasettings_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizasettings',
            name='meta',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='meta',
            field=models.TextField(default='', max_length=160),
        ),
    ]
