# Generated by Django 4.0.3 on 2022-04-12 14:36

from django.db import migrations, models
import settings_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_cotizasettings_meta_mainsettings_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='svg',
            field=models.FileField(default='', upload_to='main/', validators=[settings_app.validators.validate_file_extension]),
        ),
    ]
