# Generated by Django 4.0.3 on 2022-04-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_alter_cotizasettings_h1_alter_cotizasettings_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizasettings',
            name='meta',
            field=models.TextField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='cotizasettings',
            name='title',
            field=models.CharField(default='Limpieza de Pozos | Cotiza', max_length=50),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='meta',
            field=models.TextField(blank=True, default='', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='title',
            field=models.CharField(default='Limpieza de Pozos Sépticos | Santa Cruz', max_length=50, verbose_name='Titulo'),
        ),
    ]
